### PR TITLE
fix: fixes lint issues and generates metadata

### PR DESCRIPTION
**Pull request by g-awmalik**

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
@g-awmalik
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Review by apeabody — APPROVED** [review]

**Comment by apeabody** [comment]
Hi @g-awmalik - Probably need to add `verify_version: false` to https://github.com/terraform-google-modules/terraform-google-lb/blob/master/kitchen.yml#L17

**Comment by comment-bot-dev** [comment]
@g-awmalik
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_whitespace
 Failed whitespace check. More details below. 
 ```bash 
Checking for trailing whitespace
./kitchen.yml:31:      verify_version: false      
Error: Trailing whitespace found in the lines above.
Checking for missing newline at end of file
 ```

**Comment by comment-bot-dev** [comment]
@g-awmalik
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@g-awmalik
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Pull request merged**
